name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: investorintel-backend
          source: ./backend
          region: us-east4
          flags: --allow-unauthenticated
          env_vars: |
            AWS_REGION=${{ secrets.AWS_REGION }}
            AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}
            GEMINI_MODEL=${{ secrets.GEMINI_MODEL }}
            PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}
            SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }}
            SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }}
            SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD }}
            SNOWFLAKE_ROLE=${{ secrets.SNOWFLAKE_ROLE }}
            SNOWFLAKE_WAREHOUSE=${{ secrets.SNOWFLAKE_WAREHOUSE }}
            SNOWFLAKE_DATABASE=${{ secrets.SNOWFLAKE_DATABASE }}
            GROWJO_EMAIL=${{ secrets.GROWJO_EMAIL }}
            GROWJO_PASSWORD=${{ secrets.GROWJO_PASSWORD }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
            GOOGLE_SEARCH_ENGINE_ID=${{ secrets.GOOGLE_SEARCH_ENGINE_ID }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
          secrets: |
            AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID:latest
            AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY:latest

      - name: Show URL
        run: echo "Deployed to ${{ steps.deploy.outputs.url }}"
